# Only dedicated for:  workflow builds a k6 image for stress testing and pushes it to AWS ECR.
name: Build k6 Image for Stress Testing

on:
  workflow_dispatch:

jobs:
  build-k6:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build k6 Image
        run: |
         docker build \
           -t $ECR_REPOSITORY \
           -f k6/Dockerfile.k6Stress1000vus \
           ./k6

      - name: Tag Image
        run: |
          docker tag k6-runner:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/k6-runner:latest

      - name: Push Image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/k6-runner:latest