name: Build k6 Image for Stress Testing

on:
  workflow_dispatch:

jobs:
  build-k6:
    runs-on: ubuntu-latest

    env:
      ECR_REPOSITORY: k6-runner

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build k6 Image
        run: |
          docker build \
            -t $ECR_REPOSITORY:latest \
            -f k6/Dockerfile.k6Stress1000vus \
            ./k6

      - name: Tag Image
        run: |
          docker tag $ECR_REPOSITORY:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/k6-runner:latest

      - name: Push Image
        run: |
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/k6-runner:latest